version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: password
      POSTGRES_DB: slack_dbs
  web:
    image: slack-clone-server
    ports:
      - '3001:3001'
    networks:
      - webnet
    environment:
      HOST: db
      REDIS_HOST: redis
    command: ['./wait-for-it.sh', 'db:5432', '--', 'yarn', 'dockerstart']
networks:
  webnet:
